services:
  catalog_service:
    build:
      context: ./catalog_service
      dockerfile: Dockerfile
      args:
        - PORT=3010
        - DATABASE_URL=postgres://user:password@host.docker.internal:5432/mydatabase
    ports:
      - 3010:3010
    profiles: ["all", "catalog_service"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
  storage_manager:
    build:
      context: ./storage_manager
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=postgres://user:password@host.docker.internal:5432/mydatabase
        - STORAGE_MANAGER_HOST=tcp://0.0.0.0
        - STORAGE_MANAGER_PORT=3033
        - REPLICA_GA_HOST=tcp://acha-tally.local
        - REPLICA_GA_PORT=3034
        - STORAGE_MANAGER_REPLICA_PORT=3034
    ports:
      - 3033:3033
      - 3034:3034
    profiles: ["all", "storage_manager",  "sede-almacenamiento"]
    volumes:
      - ./acha-lib:/app/acha-lib:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
  load_manager:
    build:
      context: ./load_manager
      dockerfile: Dockerfile
      args:
        - LOAD_MANAGER_HOST=tcp://0.0.0.0
        - LOAD_MANAGER_PORT=3000
        - ACTORS_PUB_SUB_HOST=tcp://0.0.0.0
        - ACTORS_PUB_SUB_PORT=3005
        - ACTORS_CLIENT_SERVER_HOST=tcp://host.docker.internal
        - ACTORS_CLIENT_SERVER_PORT=3002
    ports:
      - 3000:3000
      - 3005:3005
    profiles: ["all", "load_manager"]
    volumes:
      - ./acha-lib:/app/acha-lib:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
  p_solicitante:
    build:
      context: ./p_solicitante
      dockerfile: Dockerfile
      args:
        - LOAD_MANAGER_HOST=tcp://host.docker.internal
        - LOAD_MANAGER_PORT=3000
        - SEDE=BOG
        - CATALOG_SERVICE_URL=http://host.docker.internal:3010
    profiles: ["all", "p_solicitante"]
    volumes:
      - ./acha-lib:/app/acha-lib:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
  actor-renew:
    build:
      context: ./actores-ts
      dockerfile: Dockerfile
      args:
        - ACTOR_LISTENING_HOST_PUBSUB=tcp://host.docker.internal
        - ACTOR_LISTENING_PORT_PUBSUB=3005
        - LOAD_MANAGER_HOST=tcp://0.0.0.0
        - LOAD_MANAGER_PORT=3002
        - STORAGE_MANAGER_HOST=tcp://host.docker.internal
        - STORAGE_MANAGER_PORT=3033
        - FALLBACK_STORAGE_MANAGER_HOST=tcp://acha-tally
        - FALLBACK_STORAGE_MANAGER_PORT=3033
    command: ["-t", "renew"]
    profiles: ["all", "actores", "sede-almacenamiento"]
    volumes:
      - ./acha-lib:/app/acha-lib:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
  actor-reserve:
    build:
      context: ./actores-ts
      dockerfile: Dockerfile
      args:
        - ACTOR_LISTENING_HOST_PUBSUB=tcp://host.docker.internal
        - ACTOR_LISTENING_PORT_PUBSUB=3005
        - LOAD_MANAGER_HOST=tcp://0.0.0.0
        - LOAD_MANAGER_PORT=3002
        - STORAGE_MANAGER_HOST=tcp://host.docker.internal
        - STORAGE_MANAGER_PORT=3033
        - FALLBACK_STORAGE_MANAGER_HOST=tcp://acha-tally
        - FALLBACK_STORAGE_MANAGER_PORT=3033
    command: ["-t", "reserve"]
    ports:
      - 3002:3002
    profiles: ["all", "actores", "sede-almacenamiento"]
    volumes:
      - ./acha-lib:/app/acha-lib:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
  actor-return:
    build:
      context: ./actores-ts
      dockerfile: Dockerfile
      args:
        - ACTOR_LISTENING_HOST_PUBSUB=tcp://host.docker.internal
        - ACTOR_LISTENING_PORT_PUBSUB=3005
        - LOAD_MANAGER_HOST=tcp://0.0.0.0
        - LOAD_MANAGER_PORT=3002
        - STORAGE_MANAGER_HOST=tcp://host.docker.internal
        - STORAGE_MANAGER_PORT=3033
        - FALLBACK_STORAGE_MANAGER_HOST=tcp://acha-tally
        - FALLBACK_STORAGE_MANAGER_PORT=3033
    command: ["-t", "return"]
    profiles: ["all", "actores", "sede-almacenamiento"]
    volumes:
      - ./acha-lib:/app/acha-lib:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/seed:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    profiles: ["all", "database", "sede-almacenamiento"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
  prisma-studio:
    build:
      context: ./prisma-studio
      dockerfile: Dockerfile
      args:
        - PORT=5555
        - DATABASE_URL=postgres://user:password@host.docker.internal:5432/mydatabase
    ports:
      - 5555:5555
    profiles: ["all", "prisma-studio", "sede-almacenamiento"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db_data:
